name = "peterson-backend"
main = "index.js"
compatibility_date = "2026-05-02"

[vars]
# No sensitive keys here, use secrets!

[[d1_databases]]
binding = "DB"
database_name = "matts-parts-db"
database_id = "d0f89a7a-2e35-473f-bf17-d1eac22f2349"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "matts-parts-photos"
